M48
; DRILL file {KiCad (7.0.0-0)} date Wednesday, 26 April 2023 at 06:05:00 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-26T18:05:00+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X125.4Y-70.425
X125.4Y-78.425
T2
X92.75Y-62.75
X92.75Y-126.0
X127.75Y-62.75
X127.75Y-126.0
T0
M30
